version: "3.7"
services:
  app:
    build:
      args:
        user: m2crud
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: M2crud-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - M2crud

  db:
    image: mysql:5.7
    container_name: M2crud-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - M2crud

  nginx:
    image: nginx:alpine
    container_name: M2crud-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - M2crud

  networks:
    M2crud:
      driver: bridge
